Repository grow/grow, pull requests merged in 2019-04, with the labels that each got.

#907 Get branch name from CI environment. Fixes #903
  grow/deployments/destinations/webreview_destination.py
Labels: enhancement

#905 Enhancements to strings preprocessor and !g.string
  grow/common/utils.py
  grow/preprocessors/google_drive.py
  grow/preprocessors/google_drive_test.py
  grow/testing/google_service.py
Labels: enhancement

#909 Adding a filter config for the routing to be able to filter routes.
  grow/commands/subcommands/build.py
  grow/commands/subcommands/deploy.py
  grow/commands/subcommands/inspect_untranslated.py
  grow/deployments/destinations/base.py
  grow/deployments/destinations/local.py
  grow/pods/env.py
  grow/routing/router.py
  grow/routing/router_test.py
  grow/routing/routes.py
  grow/routing/routes_test.py
Labels: enhancement, experiment

#911 Updating to write pod cache files even if there are rendering errors.
  grow/commands/subcommands/build.py
  grow/commands/subcommands/deploy.py
  grow/commands/subcommands/stage.py
Labels: bug

#913 Fixing filters for destinations to be more tolerant and widespread.
  grow/deployments/destinations/amazon_s3.py
  grow/deployments/destinations/base.py
  grow/deployments/destinations/git_destination.py
  grow/deployments/destinations/google_cloud_storage.py
  grow/deployments/destinations/local.py
  grow/deployments/destinations/scp.py
  grow/deployments/destinations/webreview_destination.py
Labels: bug

#916 Fixing the extension configs to be redone when the environment changes.
  grow/extensions/extension_controller.py
  grow/pods/pods.py
Labels: enhancement

#912 Updating the translations upload to update metadata after adding rows.
  grow/commands/subcommands/translations_upload.py
  grow/translators/base.py
  grow/translators/google_sheets.py
Labels: enhancement

#918 Adding ability for paths using the `{base}` to ignore index.
  grow/routing/path_format.py
  grow/routing/path_format_test.py
Labels: enhancement

#919 Drive preprocessor message for skipped tabs.
  grow/preprocessors/google_drive.py
Labels: bug

#922 Updating the AttributeDict structure to throw the correct error.
  grow/common/structures.py
Labels: bug

#925 Working to make the collection `get_doc` work better with aliases
  grow/collections/collection.py
  grow/documents/document.py
  grow/translations/locales.py
Labels: bug
