Repository grow/grow, pull requests merged in 2019-01, with the labels that each got.

#875 Reworking how markdown extensions are loaded and how md docs work.
  grow/documents/document_format.py
  grow/pods/pods.py
  grow/rendering/markdown_utils.py
  grow/rendering/markdown_utils_test.py
  grow/templates/filters.py
Labels: enhancement

#862 Passing the params to the document front matter loading.
  grow/common/utils.py
  grow/documents/document_front_matter.py
  grow/translations/catalog_holder.py
Labels: bug

#857 Removing old style routing from Grow
  grow/collections/collection_test.py
  grow/commands/shared.py
  grow/commands/subcommands/build.py
  grow/commands/subcommands/deploy.py
  grow/commands/subcommands/inspect_routes.py
  grow/commands/subcommands/inspect_stats.py
  grow/commands/subcommands/inspect_untranslated.py
  grow/commands/subcommands/install.py
  grow/commands/subcommands/preprocess.py
  grow/commands/subcommands/run.py
  grow/commands/subcommands/stage.py
  grow/commands/subcommands/translations_download.py
  grow/commands/subcommands/translations_extract.py
  grow/commands/subcommands/translations_filter.py
  grow/commands/subcommands/translations_import.py
  grow/commands/subcommands/translations_machine.py
  grow/commands/subcommands/translations_upload.py
  grow/common/markdown_extensions_test.py
  grow/deployments/stats.py
  grow/documents/document_format.py
  grow/documents/document_test.py
  grow/documents/static_document.py
  grow/extensions/core/routes_extension.py
  grow/pods/collection.py
  grow/pods/controllers.py
  grow/pods/document_fields.py
  grow/pods/document_format.py
  grow/pods/document_front_matter.py
  grow/pods/documents.py
  grow/pods/locales.py
  grow/pods/pods.py
  grow/pods/pods_test.py
  grow/pods/rendered.py
  grow/pods/rendered_test.py
  grow/pods/routes.py
  grow/pods/routes_test.py
  grow/pods/sitemap.py
  grow/pods/sitemap_test.py
  grow/pods/static.py
  grow/pods/static_test.py
  grow/pods/storage/__init__.py
  grow/pods/storage/base_storage.py
  grow/pods/storage/errors.py
  grow/pods/storage/file_storage.py
  grow/pods/storage/google_storage.py
  grow/pods/storage/storage.py
  grow/rendering/render_batch_test.py
  grow/rendering/renderer_test.py
  grow/routing/path_format.py
  grow/routing/path_format_test.py
  grow/routing/router_test.py
  grow/server/api_test.py
  grow/server/main.py
  grow/server/main_test.py
  grow/server/manager.py
  grow/templates/filters_test.py
  grow/testing/testing.py
  grow/ui/admin/views/base-reroute.html
  grow/ui/admin/views/base.html
Labels: major feature

#878 Cleaning up the way that locales are parsed and normalizing aliases
  grow/collections/collection.py
  grow/documents/document.py
  grow/documents/document_test.py
  grow/pods/pods.py
  grow/routing/path_format.py
Labels: bug

#879 Experiments in Grow
  grow/common/features.py
  grow/common/features_test.py
  grow/pods/pods.py
  grow/pods/pods_test.py
  grow/testing/testdata/pod/podspec.yaml
Labels: enhancement

#881 Making the features callable as a shortcut to test enabled features.
  grow/common/features.py
  grow/common/features_test.py
Labels: enhancement

#882 Fixing a bug with how the file is opened to write translation catalog.
  grow/translations/catalogs.py
Labels: bug

#885 Fixing how the previous doc is determined.
  grow/documents/document.py
Labels: enhancement

#890 Change html2text options to fix issues with long titles. #887
  grow/common/utils.py
Labels: bug
